const { cmd } = require('../command');
const axios = require("axios");
const fs = require("fs");
const path = require("path");

cmd({
    pattern: "web2zip",
    alias: ["getzip", "sitezip"],
    react: "📁",
    desc: "Download any website as a ZIP file",
    category: "download",
    use: ".web2zip <url>",
    filename: __filename
}, async (conn, m, mek, { from, q, reply }) => {
    try {
        if (!q) return reply("❌ *Please provide a website link!*\n\nExample: *.web2zip https://example.com*");

        reply("⏳ *Fetching and zipping the website...*\nPlease wait a few seconds ⚙️");

        // Call ElrayyXml API
        const apiUrl = `https://api.elrayyxml.web.id/api/tools/webtozip?url=${encodeURIComponent(q)}`;
        const { data } = await axios.get(apiUrl);

        if (!data.status) return reply("❌ *Failed to fetch website data!*");

        const downloadUrl = data.result?.downloadUrl;
        const fileName = (data.result?.url?.replace(/https?:\/\//, '').split('/')[0] || "website") + ".zip";

        if (!downloadUrl) return reply("⚠️ *No download link received from API!*");

        // Download the ZIP file
        const tempPath = path.join(__dirname, `../temp/${fileName}`);
        const writer = fs.createWriteStream(tempPath);

        const response = await axios({
            url: downloadUrl,
            method: 'GET',
            responseType: 'stream'
        });

        response.data.pipe(writer);

        writer.on('finish', async () => {
            await conn.sendMessage(from, {
                document: fs.readFileSync(tempPath),
                mimetype: "application/zip",
                fileName: fileName,
                caption: `✅ *Website ZIP Generated by Sʜᴀᴠɪʏᴀ-Xᴍᴅ*\n\n🌐 URL: ${data.result.url}\n📦 Files: ${data.result.copiedFilesAmount}\n👨‍💻 Author: ElrayyXml\n\n> © Powerd by Sʜᴀᴠɪʏᴀ-Xᴍᴅ👑`
            }, { quoted: mek });

            fs.unlinkSync(tempPath);
        });

        writer.on('error', (err) => {
            console.error(err);
            reply("❌ *Error while saving ZIP file.*");
        });

    } catch (e) {
        console.error(e);
        reply("❌ *Something went wrong while fetching the website!*");
    }
});
