name: WhatsApp Bot 24/7

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  bot:
    runs-on: ubuntu-latest

    steps:
      - name: Download Bot
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Start Bot
        run: |
          while true; do
            echo "Starting WhatsApp Bot..."
            npm start

            EXIT_CODE=$?
            echo "Bot stopped with exit code: $EXIT_CODE"
            echo "Restarting in 10 seconds..."
            sleep 10
          done
