name: SHAVIYA-XMD-V2-NEW

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Bot
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Start Bot
        run: |
          while true; do
            echo "================================="
            echo "Starting SHAVIYA-XMD Bot..."
            echo "================================="

            npm start

            EXIT_CODE=$?

            echo "Bot stopped!"
            echo "Exit code: $EXIT_CODE"
            echo "Restarting in 10 seconds..."

            sleep 10
          done
